import os

Import("env")
with open(env["PROJECT_TOOL_S"]) as f:
    exec(f.read())

component_dir = env.get("component_dir", os.getcwd())
projects_dir = os.path.abspath(os.path.join(component_dir, "..", ".."))
applaunch_main = os.path.join(projects_dir, "APPLaunch", "main")
emulator_vendor = os.path.join(projects_dir, "CardputerZero-Emulator", "vendor")

SRCS = Glob("src/*.c*")
INCLUDE = [
    ADir("."),
    ADir("include"),
    applaunch_main,
    os.path.join(applaunch_main, "ui", "components", "nfc"),
    emulator_vendor,
]
PRIVATE_INCLUDE = []
REQUIREMENTS = ["lvgl_component", "pthread"]
if "CONFIG_V9_5_LV_USE_SDL" not in os.environ:
    REQUIREMENTS += ["input", "xkbcommon", "udev"]
    SRCS += [os.path.join(applaunch_main, "hal", "linux", "hal_paths_linux.c")]
else:
    SRCS += [os.path.join(applaunch_main, "hal", "sdl", "hal_paths_sdl.c")]
STATIC_LIB = []
DYNAMIC_LIB = []
DEFINITIONS = ["-std=c++17"]
DEFINITIONS_PRIVATE = []
LDFLAGS = []
LINK_SEARCH_PATH = []
STATIC_FILES = []

lvgl_component = list(filter(lambda x: x["target"] == "lvgl_component", env["COMPONENTS"]))[0]
if "CONFIG_V9_5_LV_USE_SDL" in os.environ:
    lvgl_component["REQUIREMENTS"] += ["SDL2"]
    sdl_include_candidates = [
        "/usr/include/SDL2",
        "/opt/homebrew/include",
        "/opt/homebrew/include/SDL2",
    ]
    lvgl_component["INCLUDE"] += [path for path in sdl_include_candidates if os.path.exists(path)]
    if os.path.exists("/opt/homebrew/lib"):
        lvgl_component.setdefault("LINK_SEARCH_PATH", [])
        lvgl_component["LINK_SEARCH_PATH"] += ["/opt/homebrew/lib"]
    lvgl_component["DEFINITIONS"] += ["-D_REENTRANT"]

env["COMPONENTS"].append(
    {
        "target": "M5CardputerZero-RFID",
        "SRCS": SRCS,
        "INCLUDE": INCLUDE,
        "PRIVATE_INCLUDE": PRIVATE_INCLUDE,
        "REQUIREMENTS": REQUIREMENTS,
        "STATIC_LIB": STATIC_LIB,
        "DYNAMIC_LIB": DYNAMIC_LIB,
        "DEFINITIONS": DEFINITIONS,
        "DEFINITIONS_PRIVATE": DEFINITIONS_PRIVATE,
        "LDFLAGS": LDFLAGS,
        "LINK_SEARCH_PATH": LINK_SEARCH_PATH,
        "STATIC_FILES": STATIC_FILES,
        "REGISTER": "project",
    }
)
