[ssh]
local_file_path = dist
remote_file_path = /home/pi/dist
remote_host = 192.168.50.150
remote_port = 22
username = pi
password = pi
; before_cmd = 'echo pi |  sudo -S systemctl stop APPLaunch.service'
after_cmd = 'echo pi |  sudo -S systemctl stop APPLaunch.service; echo pi |  sudo -S cp /home/pi/dist/M5CardputerZero-APPLaunch /usr/share/APPLaunch/bin ; echo pi |  sudo -S systemctl start APPLaunch.service'
