// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: zero

#include "ui.h"
#include "ui_helpers.h"
#include <stdio.h>
#include <sys/stat.h>
#include "lvgl/src/widgets/gif/lv_gif.h"
#include "hal/hal_paths.h"
#include "hal/hal_audio.h"
///////////////////// VARIABLES ////////////////////



// SCREEN: ui_Screen1




#undef UI_DEFINE_OBJECT
#undef UI_DEFINE_EVENT_FUN
#define UI_DEFINE_OBJECT( x ) lv_obj_t * x ;
#define UI_DEFINE_EVENT_FUN(x) ;
#include "ui_obj.h"
#undef UI_DEFINE_OBJECT
#undef UI_DEFINE_EVENT_FUN
lv_obj_t * startup_gif;

// CUSTOM VARIABLES
int Animation_time = 200;
const char *ui_img_zero_png;
const char *ui_img_time_png;
const char *ui_img_battery_bg_png;
const char *ui_img_zuo_png;
const char *ui_img_you_png;

const char *ui_img_store_logo_png;
const char *ui_img_cli_logo_png;
const char *ui_img_claw_logo_png;
const char *ui_img_setting_logo_png;
const char *ui_img_python_logo_png;

const char *ui_img_zero_logo_w_png;
const char *ui_img_zuo_logo_png;
const char *ui_img_you_logo_png;
const char *ui_img_detail_info_png;
const char *ui_img_down_logo_png;
const char *ui_img_up_logo_png;
const char *ui_img_camera_png;

static char _img_path_buf[16][256];
static void ui_images_init(void)
{
    const char *d = hal_path_images_dir();
    struct { const char **ptr; const char *name; } tbl[] = {
        { &ui_img_zero_png,       "zero.png" },
        { &ui_img_time_png,       "time_bg.png" },
        { &ui_img_battery_bg_png, "battery_bg.png" },
        { &ui_img_zuo_png,        "zuo.png" },
        { &ui_img_you_png,        "you.png" },
        { &ui_img_zero_logo_w_png,"zero_logo_w.png" },
        { &ui_img_zuo_logo_png,   "zuo_logo.png" },
        { &ui_img_you_logo_png,   "you_logo.png" },
        { &ui_img_detail_info_png,"detail_info.png" },
        { &ui_img_down_logo_png,  "down_logo.png" },
        { &ui_img_up_logo_png,    "up_logo.png" },
        { &ui_img_camera_png,     "camera.png" },
    };
    int n = sizeof(tbl) / sizeof(tbl[0]);
    for (int i = 0; i < n && i < 16; i++) {
        snprintf(_img_path_buf[i], sizeof(_img_path_buf[i]), "%s/%s", d, tbl[i].name);
        *tbl[i].ptr = _img_path_buf[i];
    }
}






const char * font_path = NULL;
const char * mono_font_path = NULL;





static uint32_t EVT_TERM_KEY;

lv_font_t *g_font_cn_20 = NULL;
lv_font_t *g_font_cn_14 = NULL;
lv_font_t *g_font_cn_12 = NULL;
lv_font_t *g_font_mono_12 = NULL;   /* 终端专用等宽字体 */
lv_font_t *g_font_bold_20 = NULL;   /* 设置页选中项粗体 */
lv_font_t *g_font_bold_14 = NULL;   /* App名称加粗字体 - 中间 */
lv_font_t *g_font_bold_12 = NULL;   /* App名称加粗字体 - 侧面 */

// // EVENTS


///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
#include "Animation/Animation_panel.h"

// ==================== Label Animations ====================
// Labels only animate x and y (no width/height change)
// 2you direction: labels slide right (pos5→6→7→8→9)

#include "Animation/Animation_lable.h"


///////////////////// FUNCTIONS ////////////////////
#define UI_DEFINE_UI_EVENT_FUN(event_fun, call_fun) __attribute__((weak)) void event_fun(lv_event_t * e) { \
    lv_event_code_t event_code = lv_event_get_code(e); \
    if(event_code == LV_EVENT_CLICKED) { \
        call_fun(e); \
    } \
}

#include "ui_event_fun.h"



#undef UI_DEFINE_UI_EVENT_FUN



void font_manager_init(void)
{
    g_font_cn_20 = lv_freetype_font_create(
        font_path, LV_FREETYPE_FONT_RENDER_MODE_BITMAP, 20,
        LV_FREETYPE_FONT_STYLE_NORMAL);

    g_font_cn_14 = lv_freetype_font_create(
        font_path, LV_FREETYPE_FONT_RENDER_MODE_BITMAP, 14,
        LV_FREETYPE_FONT_STYLE_NORMAL);

    g_font_cn_12 = lv_freetype_font_create(
        font_path, LV_FREETYPE_FONT_RENDER_MODE_BITMAP, 12,
        LV_FREETYPE_FONT_STYLE_BOLD);

    g_font_mono_12 = lv_freetype_font_create(
        mono_font_path, LV_FREETYPE_FONT_RENDER_MODE_BITMAP, 12,
        LV_FREETYPE_FONT_STYLE_NORMAL);

    {
        static char bold_path[512];
        snprintf(bold_path, sizeof(bold_path), "%s/Montserrat-Bold.ttf", hal_path_font_dir());
        g_font_bold_20 = lv_freetype_font_create(
            bold_path, LV_FREETYPE_FONT_RENDER_MODE_BITMAP, 18,
            LV_FREETYPE_FONT_STYLE_BOLD);
        g_font_bold_14 = lv_freetype_font_create(
            bold_path, LV_FREETYPE_FONT_RENDER_MODE_BITMAP, 16,
            LV_FREETYPE_FONT_STYLE_BOLD);
        g_font_bold_12 = lv_freetype_font_create(
            bold_path, LV_FREETYPE_FONT_RENDER_MODE_BITMAP, 12,
            LV_FREETYPE_FONT_STYLE_BOLD);
    }

    // Fallback to built-in fonts if freetype loading failed (e.g. on macOS emulator)
    if (!g_font_cn_20)  g_font_cn_20  = (lv_font_t *)&lv_font_montserrat_20;
    if (!g_font_cn_14)  g_font_cn_14  = (lv_font_t *)&lv_font_montserrat_14;
    if (!g_font_cn_12)  g_font_cn_12  = (lv_font_t *)&lv_font_montserrat_12;
    if (!g_font_mono_12) g_font_mono_12 = (lv_font_t *)&lv_font_montserrat_12;
    if (!g_font_bold_20) g_font_bold_20 = (lv_font_t *)&lv_font_montserrat_18;
    if (!g_font_bold_14) g_font_bold_14 = (lv_font_t *)&lv_font_montserrat_14;
    if (!g_font_bold_12) g_font_bold_12 = (lv_font_t *)&lv_font_montserrat_12;
}

///////////////////// SCREENS ////////////////////

void home_screen_load()
{
    printf("[HOME] home_screen_load() - loading launcher home screen\n");
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
    lv_indev_set_group(lv_indev_get_next(NULL), Screen1group);

    static char _startup_snd[256];
    snprintf(_startup_snd, sizeof(_startup_snd), "%s/startup.mp3", hal_path_images_dir());
    hal_audio_play(_startup_snd);
}

void audio_system_init();
void audio_load_sounds();

void ui_event_logo_over(lv_event_t * e) {
    static int done = 0;
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_READY && !done) {
        done = 1;
        printf("[GIF] first LV_EVENT_READY -> pause + home_screen_load()\n");
        if (startup_gif) lv_gif_pause(startup_gif);


        /*
        * 这里会在程序运行时执行一次。
        * 所以在这里初始化音频最合适。
        *
        * audio_system_init():
        *   打开 ALSA 设备，并保持打开。
        *
        * audio_load_sounds():
        *   预加载 switch.wav / enter.wav。
        */
        audio_system_init();
        audio_load_sounds();

        home_screen_load();
    }
}

static char _gif_path[256];
void start_startup_gif()
{
    snprintf(_gif_path, sizeof(_gif_path), "%s/logo_output.gif", hal_path_images_dir());
    startup_gif = lv_gif_create(NULL);
    lv_gif_set_src(startup_gif, _gif_path);
    lv_obj_center(startup_gif);
    lv_obj_add_event_cb(startup_gif, ui_event_logo_over, LV_EVENT_ALL, NULL);
    lv_disp_load_scr(startup_gif);
}

void ui_init(void)
{
    hal_paths_init(NULL);
    ui_images_init();
    font_path = hal_path_font_regular();
    mono_font_path = hal_path_font_mono();
    font_manager_init();

    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);

    // 初始化各个界面
    ui_Screen1_screen_init();

    // 界面信息绑定
    ui_info_bind();
    launch_circle_init();

    // 初始化输入组
    input_group_init();

    // 显示开机动画（需要 share/images/logo_output.gif）
#ifndef APPLAUNCH_STARTUP_ANIMATION
    home_screen_load();
#else
    #ifdef HAL_PLATFORM_SDL
    home_screen_load();
    #else
    {
        char gif_check[256];
        snprintf(gif_check, sizeof(gif_check), "%s/logo_output.gif", hal_path_images_dir());
        FILE *_gif_f = fopen(gif_check, "r");
        if (_gif_f) { fclose(_gif_f); start_startup_gif(); }
        else { home_screen_load(); }
    }
    #endif
#endif
}



char* cimg_path(const char *name)
{
    static char path_buf[512];
    snprintf(path_buf, sizeof(path_buf), "%s%s%s", hal_path_images_dir(), PATH_SEP, name);
    return path_buf;
}

char* caudio_path(const char *name)
{
    static char path_buf[512];
    snprintf(path_buf, sizeof(path_buf), "%s%s%s", hal_path_audio_dir(), PATH_SEP, name);
    return path_buf;
}

char* cfont_path(const char *name)
{
    static char path_buf[512];
    snprintf(path_buf, sizeof(path_buf), "%s%s%s", hal_path_font_dir(), PATH_SEP, name);
    return path_buf;
}