// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: zero

#ifndef _ZERO_UI_H
#define _ZERO_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
#include "ui_input_group.h"
#include "keyboard_input.h"
#include "hal/hal_settings.h"

#define lv_mem_alloc lv_malloc
#define lv_mem_free   lv_free
#define lv_event_send(obj, evt, param) lv_obj_send_event(obj, evt, param)

// typedef void (*ui_anim_ready_cb_t)(lv_anim_t * a);
typedef void (*ui_anim_ready_cb_t)(lv_anim_t *);

void zuopanel2you_Animation(lv_obj_t * TargetObject, int delay, ui_anim_ready_cb_t ready_cb);
void switchpanel2you_Animation(lv_obj_t * TargetObject, int delay, ui_anim_ready_cb_t ready_cb);
void youpanel2you_Animation(lv_obj_t * TargetObject, int delay, ui_anim_ready_cb_t ready_cb);
void zuopanelout2you_Animation(lv_obj_t * TargetObject, int delay, ui_anim_ready_cb_t ready_cb);
void zuopanel2zuo_Animation(lv_obj_t * TargetObject, int delay, ui_anim_ready_cb_t ready_cb);
void switchpanel2zuo_Animation(lv_obj_t * TargetObject, int delay, ui_anim_ready_cb_t ready_cb);
void youpanel2zuo_Animation(lv_obj_t * TargetObject, int delay, ui_anim_ready_cb_t ready_cb);
void zuopanelout2zuo_Animation(lv_obj_t * TargetObject, int delay, ui_anim_ready_cb_t ready_cb);
// Label animations - 2you direction
void zuolabelout2you_Animation(lv_obj_t * TargetObject, int delay, ui_anim_ready_cb_t ready_cb);
void zuolabel2you_Animation(lv_obj_t * TargetObject, int delay, ui_anim_ready_cb_t ready_cb);
void switchlabel2you_Animation(lv_obj_t * TargetObject, int delay, ui_anim_ready_cb_t ready_cb);
void youlabel2you_Animation(lv_obj_t * TargetObject, int delay, ui_anim_ready_cb_t ready_cb);
// Label animations - 2zuo direction
void zuolabelout2zuo_Animation(lv_obj_t * TargetObject, int delay, ui_anim_ready_cb_t ready_cb);
void youlabel2zuo_Animation(lv_obj_t * TargetObject, int delay, ui_anim_ready_cb_t ready_cb);
void switchlabel2zuo_Animation(lv_obj_t * TargetObject, int delay, ui_anim_ready_cb_t ready_cb);
void zuolabel2zuo_Animation(lv_obj_t * TargetObject, int delay, ui_anim_ready_cb_t ready_cb);
// SCREEN: ui_Screen1

void ui_Screen1_screen_init(void);


void launch_circle_init();
void ui_info_bind();






#define LV_EVENT_KEYBOARD_GET_KEY(e) ((struct key_item *)lv_event_get_param(e))->key_code
#define LV_EVENT_KEYBOARD_GET_KEY_STATE(e) ((struct key_item *)lv_event_get_param(e))->key_state
#define IS_KEY_PRESSED(e) ((lv_event_get_code(e) == LV_EVENT_KEYBOARD)&&(LV_EVENT_KEYBOARD_GET_KEY_STATE(e) > 0))
#define IS_KEY_RELEASED(e) ((lv_event_get_code(e) == LV_EVENT_KEYBOARD)&&(LV_EVENT_KEYBOARD_GET_KEY_STATE(e) == 0))

extern volatile uint32_t LV_EVENT_BATTERY;

typedef struct {
    hal_battery_info_t info;
} lv_battery_event_data_t;

#define LV_EVENT_BATTERY_GET_INFO(e) (&((lv_battery_event_data_t *)lv_event_get_param(e))->info)


#undef UI_DEFINE_OBJECT
#undef UI_DEFINE_EVENT_FUN
#define UI_DEFINE_OBJECT( x ) extern lv_obj_t * x ;
#define UI_DEFINE_EVENT_FUN( x ) void x(lv_event_t * e);
#include "ui_obj.h"
#undef UI_DEFINE_OBJECT
#undef UI_DEFINE_EVENT_FUN




#define UI_DEFINE_UI_EVENT_FUN(event_fun, call_fun) void event_fun(lv_event_t * e);

#include "ui_event_fun.h"
#undef UI_DEFINE_UI_EVENT_FUN


lv_obj_t * ui_console_creat(lv_event_t * e);
void ui_console_exit(lv_event_t * e);
void ui_console_key(lv_event_t * e);



// CUSTOM VARIABLES
extern const char *ui_img_zero_png;
extern const char *ui_img_time_png;
extern const char *ui_img_battery_bg_png;
extern const char *ui_img_zuo_png;
extern const char *ui_img_you_png;
extern const char *ui_img_store_logo_png ;
extern const char *ui_img_cli_logo_png   ;
extern const char *ui_img_claw_logo_png  ;
extern const char *ui_img_setting_logo_png ;
extern const char *ui_img_python_logo_png ;





extern const char *ui_img_zero_logo_w_png ;
extern const char *ui_img_zuo_logo_png ;
extern const char *ui_img_you_logo_png ;
extern const char *ui_img_detail_info_png ;
extern const char *ui_img_down_logo_png ;
extern const char *ui_img_up_logo_png ;
extern const char *ui_img_camera_png ;


extern lv_font_t *g_font_cn_20;
extern lv_font_t *g_font_cn_14;
extern lv_font_t *g_font_cn_12;
extern lv_font_t *g_font_mono_12;
extern lv_font_t *g_font_bold_20;
extern lv_font_t *g_font_bold_14;
extern lv_font_t *g_font_bold_12;
// Launcher layout constants
#define BORDER_COLOR_CENTER  0x444444
#define BORDER_COLOR_SIDE    0x222222
#define LABEL_Y_CENTER       50
#define LABEL_Y_SIDE         50

// EVENTS
extern lv_obj_t * ui____initial_actions0;

#ifdef _WIN32
    #define PATH_SEP "\\"
#else
    #define PATH_SEP "/"
#endif
char* cimg_path(const char *name);
char* caudio_path(const char *name);
char* cfont_path(const char *name);


// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
